---
# Install operators packages

- name: unwanted packages are removed
  package:
    name: "{{ operators_packages_remove }}"
    state: absent
  become: true
  when: operators_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ operators_packages_repos }}"
    state: "{{ operators_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ operators_packages_prereq }}"
    state: "{{ operators_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ operators_packages_install }}"
    state: "{{ operators_packages_state }}"
  become: true
